name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout ved
      uses: actions/checkout@v2
      with:
        path: ved
    - name: Build V
      run: make
    # - name: v vet
    #   run: |
    #     v vet .
    - name: v fmt -verify
      # v fmt -verify timer.v
      run: |
        cd ved
        ../v fmt -verify config.v query.v ved.v view.v

  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout ved
      uses: actions/checkout@v2
      with:
        path: ved
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y libfreetype6-dev libglfw3-dev libxi-dev libxcursor-dev
    - name: Build V
      run: make
    - name: Build ved
      run: |
        cd ved
        ../v -prod .
        ../v -autofree .

  macos:
    runs-on: macos-10.15
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout ved
      uses: actions/checkout@v2
      with:
        path: ved
    - name: Build V
      run: make
    - name: Build ved
      run: |
        cd ved
        ../v .
        #v -prod .

  windows:
    runs-on: windows-2019
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout ved
      uses: actions/checkout@v2
      with:
        path: ved
    - name: Build V
      run: |
        .\make.bat -gcc
    - name: Build ved
      run: |
        cd ved
        ..\v.exe -prod .
